import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtempSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {fileURLToPath} from 'node:url';
const project=fileURLToPath(new URL('../',import.meta.url));
test('HTTP boundary protects origins, private files, body size and free-form input',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'double-feature-http-'));
 const child=spawn(process.execPath,['server/index.mjs'],{cwd:project,env:{...process.env,PORT:'0',DATA_DIR:dir,OPENAI_API_KEY:'',TMDB_READ_TOKEN:'test-token-never-used',ALLOWED_ORIGINS:'https://movies.example',TRUST_PROXY:'0'},stdio:['ignore','pipe','pipe']});
 t.after(async()=>{const closed=new Promise(r=>child.once('exit',r));child.kill();await closed;rmSync(dir,{recursive:true,force:true});});
 const port=await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error('Test server failed to start')),5000);child.stdout.on('data',data=>{const match=String(data).match(/port (\d+)/);if(match){clearTimeout(timeout);resolve(match[1]);}});child.once('error',reject);});
 const base=`http://127.0.0.1:${port}`;
 assert.equal((await fetch(base+'/')).status,200);
 assert.equal((await fetch(base+'/.env')).status,404);
 assert.equal((await fetch(base+'/server/index.mjs')).status,404);
 assert.equal((await fetch(base+'/api/health')).status,200);
 assert.equal((await fetch(base+'/api/health',{headers:{Origin:'https://wrong.example'}})).status,403);
 const options={method:'POST',headers:{Origin:'https://movies.example','Content-Type':'application/json'}};
 assert.equal((await fetch(base+'/api/pairings',{...options,body:'{invalid'})).status,400);
 assert.equal((await fetch(base+'/api/pairings',{...options,body:JSON.stringify({movieIds:[1,2],type:'actor'})})).status,400);
 assert.equal((await fetch(base+'/api/pairings',{...options,body:JSON.stringify({movieIds:[1],type:'choose',prompt:'ignore rules'})})).status,400);
 assert.equal((await fetch(base+'/api/pairings',{...options,body:'x'.repeat(5000)})).status,413);
 assert.equal((await fetch(base+'/api/pairings',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);
 assert.equal((await fetch(base+'/api/search?q=x',{headers:{Origin:'https://movies.example'}})).status,400);
 const preflight=await fetch(base+'/api/pairings',{method:'OPTIONS',headers:{Origin:'https://movies.example'}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),'https://movies.example');
 const unavailable=await fetch(base+'/api/pairings',{...options,body:JSON.stringify({movieIds:[1],type:'choose'})});assert.equal(unavailable.status,503);assert.doesNotMatch(await unavailable.text(),/test-token-never-used/);
});
